name: Deploy Website

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: check code
      uses: actions/checkout@v4
      
    - name: Executing remote SSH commands using SSH key
      uses: appleboy/ssh-action@v1.0.3
      with:
          host: ${{ secrets.SSH_HOST}}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /${{ secrets.SSH_USERNAME }}/hetaoshu
            git pull
            docker compose down
            docker compose up --build -d
